
package GUI;

import java.awt.*;

/**
 *
 * @author Admin
 */
public class Create_new_account extends javax.swing.JFrame {

    /**
     * Creates new form Create_new_account
     */
    public Create_new_account() {

        initComponents();
        jPanel1.setFocusable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_admin = new javax.swing.JCheckBox();
        btn_dk = new javax.swing.JButton();
        txt_cccd = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_repw = new javax.swing.JPasswordField();
        txt_name = new javax.swing.JTextField();
        lb_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create new account");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Đăng ký tài khoản");

        cb_admin.setBackground(new java.awt.Color(255, 255, 255));
        cb_admin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cb_admin.setForeground(new java.awt.Color(0, 0, 0));
        cb_admin.setText("Đăng ký tài khoản Admin");
        cb_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_adminActionPerformed(evt);
            }
        });

        btn_dk.setBackground(new java.awt.Color(66, 183, 42));
        btn_dk.setForeground(new java.awt.Color(255, 255, 255));
        btn_dk.setText("Đăng ký");
        btn_dk.setBorder(null);
        btn_dk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dkActionPerformed(evt);
            }
        });

        txt_cccd.setBackground(new java.awt.Color(255, 255, 255));
        txt_cccd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cccd.setForeground(new java.awt.Color(153, 153, 153));
        txt_cccd.setText("Số CCCD");
        txt_cccd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cccdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cccdFocusLost(evt);
            }
        });

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(153, 153, 153));
        txt_username.setText("Tên tài khoản");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(153, 153, 153));
        txt_password.setText("Mật khẩu");
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });

        txt_repw.setBackground(new java.awt.Color(255, 255, 255));
        txt_repw.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_repw.setForeground(new java.awt.Color(153, 153, 153));
        txt_repw.setText("Nhập lại mật khẩu");
        txt_repw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_repwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_repwFocusLost(evt);
            }
        });

        txt_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_name.setForeground(new java.awt.Color(153, 153, 153));
        txt_name.setText("Họ và tên");
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });

        lb_back.setBackground(new java.awt.Color(255, 255, 255));
        lb_back.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lb_back.setForeground(new java.awt.Color(153, 153, 153));
        lb_back.setText("←");
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(118, 118, 118)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_repw, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(169, 169, 169)
                                                .addComponent(cb_admin))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(207, 207, 207)
                                                .addComponent(btn_dk, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(jLabel3))
                                        .addComponent(lb_back))
                                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txt_repw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_admin)
                                .addGap(18, 18, 18)
                                .addComponent(btn_dk, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {
        if(txt_name.getText().equals("Họ và tên")){
            txt_name.setText("");
            txt_name.setForeground(Color.black);
        }
    }

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {
        if(txt_name.getText().trim().equals("")||txt_cccd.getText().trim().toLowerCase().equals("Họ và tên")){
            txt_name.setText("Họ và tên");
            txt_name.setForeground(new Color(153,153,153));
        }
    }

    private void txt_cccdFocusGained(java.awt.event.FocusEvent evt) {
        if(txt_cccd.getText().equals("Số CCCD")){
            txt_cccd.setText("");
            txt_cccd.setForeground(Color.black);
        }
    }

    private void txt_cccdFocusLost(java.awt.event.FocusEvent evt) {
        if(txt_cccd.getText().trim().equals("")||txt_cccd.getText().trim().toLowerCase().equals("Số CCCD")){
            txt_cccd.setText("Số CCCD");
            txt_cccd.setForeground(new Color(153,153,153));
        }
    }

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {
        if(txt_username.getText().equals("Tên tài khoản")){
            txt_username.setText("");
            txt_username.setForeground(Color.black);
        }
    }

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {
        if(txt_username.getText().trim().equals("")||txt_cccd.getText().trim().toLowerCase().equals("Tên tài khoản")){
            txt_username.setText("Tên tài khoản");
            txt_username.setForeground(new Color(153,153,153));
        }
    }

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {
        String s = new StringBuilder().append("").append(txt_password.getPassword()).toString();
        if(s.equals("Mật khẩu")){
            txt_password.setText("");
            txt_password.setEchoChar('•');
            txt_password.setForeground(Color.black);}
    }

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {
        String s = new StringBuilder().append("").append(txt_password.getPassword()).toString();
        if(s.trim().equals("")||s.trim().toLowerCase().equals("Mật khẩu")){
            txt_password.setEchoChar((char)0);
            txt_password.setText("Mật khẩu");
            txt_password.setForeground(new Color(153,153,153));
        }
    }

    private void txt_repwFocusGained(java.awt.event.FocusEvent evt) {
        String s = new StringBuilder().append("").append(txt_repw.getPassword()).toString();
        if(s.equals("Nhập lại mật khẩu")){
            txt_repw.setText("");
            txt_repw.setEchoChar('•');
            txt_repw.setForeground(Color.black);}
    }

    private void txt_repwFocusLost(java.awt.event.FocusEvent evt) {
        String s = new StringBuilder().append("").append(txt_repw.getPassword()).toString();
        if(s.trim().equals("")||s.trim().toLowerCase().equals("Nhập lại mật khẩu")){
            txt_repw.setEchoChar((char)0);
            txt_repw.setText("Nhập lại mật khẩu");
            txt_repw.setForeground(new Color(153,153,153));
        }
    }

    private void cb_adminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_dkActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {
        Log_in log_in = new Log_in();
        log_in.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_new_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_dk;
    private javax.swing.JCheckBox cb_admin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_back;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_repw;
    private javax.swing.JTextField txt_username;
    // End of variables declaration
}
